profile: null
region: us-east-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: alexa-irkit
  runtime: python2.7
  role: arn:aws:lambda:us-east-1:180047737375:function:alexa-irkit
  handler: lambda_function.lambda_handler
  description: This is a sample lambda function.
  timeout: 10
  memory_size: 128
