profile: null
region: us-east-1
versioning: false
default_alias: null
clean_build: false
configuration:
  name: alexa-irkit
  runtime: python2.7
  role: arn:aws:iam::180047737375:role/lambda_basic_execution
  handler: lambda_function.lambda_handler
  description: Cooperation alexa and irkit
  timeout: 10
  memory_size: 128
